# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.createTask = QtWidgets.QPushButton(self.groupBox)
        self.createTask.setObjectName("createTask")
        self.horizontalLayout.addWidget(self.createTask)
        self.changeTask = QtWidgets.QPushButton(self.groupBox)
        self.changeTask.setObjectName("changeTask")
        self.horizontalLayout.addWidget(self.changeTask)
        self.deleteTask = QtWidgets.QPushButton(self.groupBox)
        self.deleteTask.setObjectName("deleteTask")
        self.horizontalLayout.addWidget(self.deleteTask)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.taskList = QtWidgets.QListWidget(self.groupBox)
        self.taskList.setObjectName("taskList")
        self.gridLayout.addWidget(self.taskList, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.viewDescription = QtWidgets.QListView(self.groupBox_2)
        self.viewDescription.setObjectName("viewDescription")
        self.verticalLayout_2.addWidget(self.viewDescription)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 4, 4, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.viewComments = QtWidgets.QListView(self.groupBox_2)
        self.viewComments.setObjectName("viewComments")
        self.verticalLayout_4.addWidget(self.viewComments)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textComment = QtWidgets.QTextEdit(self.groupBox_2)
        self.textComment.setAutoFillBackground(False)
        self.textComment.setDocumentTitle("")
        self.textComment.setObjectName("textComment")
        self.horizontalLayout_4.addWidget(self.textComment, 0, QtCore.Qt.AlignBottom)
        self.addComment = QtWidgets.QPushButton(self.groupBox_2)
        self.addComment.setObjectName("addComment")
        self.horizontalLayout_4.addWidget(self.addComment)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 6, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.viewPeple = QtWidgets.QListView(self.groupBox_2)
        self.viewPeple.setObjectName("viewPeple")
        self.verticalLayout.addWidget(self.viewPeple)
        self.gridLayout_3.addLayout(self.verticalLayout, 3, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.viewMaker = QtWidgets.QLineEdit(self.groupBox_2)
        self.viewMaker.setObjectName("viewMaker")
        self.horizontalLayout_3.addWidget(self.viewMaker)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.viewTopic = QtWidgets.QLineEdit(self.groupBox_2)
        self.viewTopic.setObjectName("viewTopic")
        self.horizontalLayout_2.addWidget(self.viewTopic)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.viewStatus = QtWidgets.QLineEdit(self.groupBox_2)
        self.viewStatus.setObjectName("viewStatus")
        self.horizontalLayout_2.addWidget(self.viewStatus)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 4, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.viewDate = QtWidgets.QLineEdit(self.groupBox_2)
        self.viewDate.setObjectName("viewDate")
        self.horizontalLayout_6.addWidget(self.viewDate)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 5, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Список задач"))
        self.createTask.setText(_translate("MainWindow", "Create Task"))
        self.changeTask.setText(_translate("MainWindow", "ChangeTask"))
        self.deleteTask.setText(_translate("MainWindow", "Delete Task"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Задача"))
        self.label_5.setText(_translate("MainWindow", "Описание"))
        self.label_6.setText(_translate("MainWindow", "Комментарии"))
        self.textComment.setPlaceholderText(_translate("MainWindow", "Напишите комментарий"))
        self.addComment.setText(_translate("MainWindow", "Отправить"))
        self.label_4.setText(_translate("MainWindow", "Участники"))
        self.label_3.setText(_translate("MainWindow", "Создатель"))
        self.label.setText(_translate("MainWindow", "Тема"))
        self.label_2.setText(_translate("MainWindow", "Статус"))
        self.label_7.setText(_translate("MainWindow", "Срок выполнения"))

